version: '3.9'

services:
  df.menuservice.api:
    image: df.menuservice.api
    build:
      context: .
      dockerfile: DF.MenuService.API/Dockerfile
    container_name: df.menuservice.api
    ports:
      - "5004:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=df.menuservice.db;Port=5432;Database=MenuServiceDb;Username=MenuService;Password=MenuService2025!
      Redis__Host: df.redis
      Redis__Port: 6379
    depends_on:
      - df.menuservice.db
      - df.redis
    networks:
      - df-network

  df.menuservice.db:
    image: postgres:16
    container_name: df.menuservice.db
    environment:
      POSTGRES_USER: MenuService
      POSTGRES_PASSWORD: MenuService2025!
      POSTGRES_DB: MenuServiceDb
    ports:
      - "5433:5432"
    volumes:
      - menu_service_data:/var/lib/postgresql/data
    networks:
      - df-network

  df.redis:
    image: redis:7
    container_name: df.redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - df-network

volumes:
  menu_service_data:
  redis_data:

networks:
  df-network:
    external: true
