version: '3.9'

services:
  df.userservice.api:
    image: df.userservice.api
    build:
      context: .
      dockerfile: DF.UserService.API/Dockerfile
    container_name: df.userservice.api
    ports:
      - "5000:5000"
    depends_on:
      - mssql
      - rabbitmq
    networks:
      - df-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: StrongPass123!
    ports:
      - "11433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - df-network
  
  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    volumes:
      - ./init.sql:/init.sql
    entrypoint: >
      /bin/bash -c "
      sleep 20;
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P StrongPass123! -i /init.sql
      "

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - df-network

volumes:
  mssql_data:

networks:
  df-network:
    external: true
