# This is a generated file. Not intended for manual editing.
services:
  df.orderservice.api:
    build:
      context: "C:\\Users\\User\\Desktop\\Я\\Projects\\food-delivery-platform\\backend\\\
        OrderService"
      dockerfile: "DF.OrderService.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/DF.OrderService.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "df.orderservice.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\User\\Desktop\\Я\\Projects\\food-delivery-platform\\backend\\OrderService\\\
      DF.OrderService.API:/app:rw"
    - "C:\\Users\\User\\Desktop\\Я\\Projects\\food-delivery-platform\\backend\\OrderService:/src:rw"
    - "C:\\Users\\User\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
